server {
    listen 80;
    server_name localhost;

    # Serveur du Frontend (fichiers statiques)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy pour Keycloak (Accès externe /auth/ -> Interne /)
    location /auth/ {
        proxy_pass http://keycloak:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /auth;
        proxy_redirect off;
    }

    # Proxy pour Microservice AUTH
    location /api/auth/ {
        proxy_pass http://ms-auth:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy pour Microservice ADMIN
    location /api/admin/ {
        proxy_pass http://ms-admin:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy pour Microservice FICHIERS
    location /api/fichiers/ {
        proxy_pass http://ms-fichiers:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy pour Microservice TELECHARGEMENT
    location /api/telechargement/ {
        proxy_pass http://ms-telechargement:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy pour Microservice IA
    location /api/ia/ {
        proxy_pass http://ms-ia:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy pour MinIO (Téléchargement de fichiers)
    location /minio/ {
        proxy_pass http://minio:9000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
